TrajectoryPlannerROS:
        max_vel_x: 0.3
        min_vel_x: 0.05
        max_vel_theta: 0.05
        min_in_place_vel_theta: 0.01
        acc_lim_theta: 10
        acc_lim_x: 10
        acc_lim_y: 10
        holonomic_robot: true
        yaw_goal_tolerance: 0.1
        xy_goal_tolerance: 0.1
