obstacle_range: 0.5
raytrace_range: 2.0
robot_radius: 0.14
inflation_radius: 0.05
observation_sources: laser
laser: { sensor_frame: laser, data_type: LaserScan, topic: laser, marking: true, clearing: true }

