DWAPlannerROS:
        max_trans_vel: 0.5
        min_trans_vel: 0.3
        max_vel_x: 0.5
        min_vel_x: 0.3
        max_vel_y: 0
        min_vel_y: 0
        max_rot_vel: 0.3
        min_rot_vel: 0.25
        acc_lim_theta: 0.2
        acc_lim_x: 1
        acc_lim_y: 0
        yaw_goal_tolerance: 0.1
        xy_goal_tolerance: 0.1
