FROM ros:kinetic-robot
SHELL ["/bin/bash", "-c"]

COPY ./docker/docker-entrypoint.sh /
ENTRYPOINT [ "/docker-entrypoint.sh" ]

# Prepare ROS Dep.
RUN echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list \
    && apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' \
    --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654 \
    && apt-get update -y \
    && apt-get upgrade -y \
    && apt-get install -y \
        python-catkin-tools \
        cmake \
        ros-kinetic-joy \
        ros-kinetic-move-base-msgs \
        ros-kinetic-rviz \
        ros-kinetic-rosserial \
        ros-kinetic-rosserial-server

RUN git clone https://github.com/WiringPi/WiringPi.git \
    && cd WiringPi \
    && ./build

# Initialize Trinity Catkin Workspace
RUN mkdir -p /home/ros/catkin_ws/src \
    && cd /home/ros/catkin_ws/ \
    && catkin init

# Copy & Configure Trinity Source
# COPY src /home/ros/catkin_ws/src
COPY ./docker/wait_for_core.sh /home/ros/
RUN rosdep update && rosdep install \
    --from-paths /home/ros/catkin_ws/src \
    --ignore-src \
    --rosdistro kinetic \
    -y

# Catkin Build
WORKDIR /home/ros/catkin_ws/
